dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - "npm run build"
  - "npm run test -- --watch=false"
  - "npm run lint"
  - "npm run e2e"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search