dist: focal
os: linux

addons:
  chrome: stable

language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - "npx ng lint ng-event-options"
  - "npx ng test ng-event-options --code-coverage --watch=false"
  - "npx ng build ng-event-options -c=production"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/ng-event-options/lcov.info --disable search
