dist: trusty
sudo: true

addons:
  apt:
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - "npx ng test --code-coverage --watch=false"
  - "npx ng lint"
  - "npx ng e2e"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/ng-event-options/lcov.info --disable search
